using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GoogleTranslateFree
{
    public static class Languages
    {
        public static List<LanguageModel> langs = new List<LanguageModel>()
        {
            new LanguageModel("auto" , "Automatic"),
            new LanguageModel("af" , "Afrikaans"),
            new LanguageModel("sq" , "Albanian"),
            new LanguageModel("am" , "Amharic"),
            new LanguageModel("ar" , "Arabic"),
            new LanguageModel("hy" , "Armenian"),
            new LanguageModel("az" , "Azerbaijani"),
            new LanguageModel("eu" , "Basque"),
            new LanguageModel("be" , "Belarusian"),
            new LanguageModel("bn" , "Bengali"),
            new LanguageModel("bs" , "Bosnian"),
            new LanguageModel("bg" , "Bulgarian"),
            new LanguageModel("ca" , "Catalan"),
            new LanguageModel("ceb" , "Cebuano"),
            new LanguageModel("ny" , "Chichewa"),
            new LanguageModel("zh-cn" , "Chinese Simplified"),
            new LanguageModel("zh-tw" , "Chinese Traditional"),
            new LanguageModel("co" , "Corsican"),
            new LanguageModel("hr" , "Croatian"),
            new LanguageModel("cs" , "Czech"),
            new LanguageModel("da" , "Danish"),
            new LanguageModel("nl" , "Dutch"),
            new LanguageModel("en" , "English"),
            new LanguageModel("eo" , "Esperanto"),
            new LanguageModel("et" , "Estonian"),
            new LanguageModel("tl" , "Filipino"),
            new LanguageModel("fi" , "Finnish"),
            new LanguageModel("fr" , "French"),
            new LanguageModel("fy" , "Frisian"),
            new LanguageModel("gl" , "Galician"),
            new LanguageModel("ka" , "Georgian"),
            new LanguageModel("de" , "German"),
            new LanguageModel("el" , "Greek"),
            new LanguageModel("gu" , "Gujarati"),
            new LanguageModel("ht" , "Haitian Creole"),
            new LanguageModel("ha" , "Hausa"),
            new LanguageModel("haw" , "Hawaiian"),
            new LanguageModel("iw" , "Hebrew"),
            new LanguageModel("hi" , "Hindi"),
            new LanguageModel("hmn" , "Hmong"),
            new LanguageModel("hu" , "Hungarian"),
            new LanguageModel("is" , "Icelandic"),
            new LanguageModel("ig" , "Igbo"),
            new LanguageModel("id" , "Indonesian"),
            new LanguageModel("ga" , "Irish"),
            new LanguageModel("it" , "Italian"),
            new LanguageModel("ja" , "Japanese"),
            new LanguageModel("jw" , "Javanese"),
            new LanguageModel("kn" , "Kannada"),
            new LanguageModel("kk" , "Kazakh"),
            new LanguageModel("km" , "Khmer"),
            new LanguageModel("ko" , "Korean"),
            new LanguageModel("ku" , "Kurdish (Kurmanji)"),
            new LanguageModel("ky" , "Kyrgyz"),
            new LanguageModel("lo" , "Lao"),
            new LanguageModel("la" , "Latin"),
            new LanguageModel("lv" , "Latvian"),
            new LanguageModel("lt" , "Lithuanian"),
            new LanguageModel("lb" , "Luxembourgish"),
            new LanguageModel("mk" , "Macedonian"),
            new LanguageModel("mg" , "Malagasy"),
            new LanguageModel("ms" , "Malay"),
            new LanguageModel("ml" , "Malayalam"),
            new LanguageModel("mt" , "Maltese"),
            new LanguageModel("mi" , "Maori"),
            new LanguageModel("mr" , "Marathi"),
            new LanguageModel("mn" , "Mongolian"),
            new LanguageModel("my" , "Myanmar (Burmese)"),
            new LanguageModel("ne" , "Nepali"),
            new LanguageModel("no" , "Norwegian"),
            new LanguageModel("ps" , "Pashto"),
            new LanguageModel("fa" , "Persian"),
            new LanguageModel("pl" , "Polish"),
            new LanguageModel("pt" , "Portuguese"),
            new LanguageModel("ma" , "Punjabi"),
            new LanguageModel("ro" , "Romanian"),
            new LanguageModel("ru" , "Russian"),
            new LanguageModel("sm" , "Samoan"),
            new LanguageModel("gd" , "Scots Gaelic"),
            new LanguageModel("sr" , "Serbian"),
            new LanguageModel("st" , "Sesotho"),
            new LanguageModel("sn" , "Shona"),
            new LanguageModel("sd" , "Sindhi"),
            new LanguageModel("si" , "Sinhala"),
            new LanguageModel("sk" , "Slovak"),
            new LanguageModel("sl" , "Slovenian"),
            new LanguageModel("so" , "Somali"),
            new LanguageModel("es" , "Spanish"),
            new LanguageModel("su" , "Sundanese"),
            new LanguageModel("sw" , "Swahili"),
            new LanguageModel("sv" , "Swedish"),
            new LanguageModel("tg" , "Tajik"),
            new LanguageModel("ta" , "Tamil"),
            new LanguageModel("te" , "Telugu"),
            new LanguageModel("th" , "Thai"),
            new LanguageModel("tr" , "Turkish"),
            new LanguageModel("uk" , "Ukrainian"),
            new LanguageModel("ur" , "Urdu"),
            new LanguageModel("uz" , "Uzbek"),
            new LanguageModel("vi" , "Vietnamese"),
            new LanguageModel("cy" , "Welsh"),
            new LanguageModel("xh" , "Xhosa"),
            new LanguageModel("yi" , "Yiddish"),
            new LanguageModel("yo" , "Yoruba"),
            new LanguageModel("zu" , "Zulu")
        };

    }
}
